2018-04-23 10:45:04,537:INFO:Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
2018-04-23 10:45:25,099:ERROR:Caught an exception during parse: list index out of range
Traceback (most recent call last):
  File "C:/Users/IT/Desktop/ticket-bot/server.py", line 93, in respond
    response = self.filter_agent_response(message, sender_id, parse_data, [response_data[0].get('text')])
IndexError: list index out of range
2018-04-23 10:45:44,598:ERROR:Caught an exception during parse: list index out of range
Traceback (most recent call last):
  File "C:/Users/IT/Desktop/ticket-bot/server.py", line 93, in respond
    response = self.filter_agent_response(message, sender_id, parse_data, [response_data[0].get('text')])
IndexError: list index out of range
2018-04-23 10:45:48,525:ERROR:Caught an exception during parse: list index out of range
Traceback (most recent call last):
  File "C:/Users/IT/Desktop/ticket-bot/server.py", line 93, in respond
    response = self.filter_agent_response(message, sender_id, parse_data, [response_data[0].get('text')])
IndexError: list index out of range
2018-04-23 10:46:23,547:ERROR:Caught an exception during parse: list index out of range
Traceback (most recent call last):
  File "C:/Users/IT/Desktop/ticket-bot/server.py", line 93, in respond
    response = self.filter_agent_response(message, sender_id, parse_data, [response_data[0].get('text')])
IndexError: list index out of range
2018-04-23 10:47:30,790:INFO:Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
2018-04-23 11:08:31,825:INFO:Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
2018-04-23 11:19:21,357:ERROR:Caught an exception during parse: list index out of range
Traceback (most recent call last):
  File "C:/Users/IT/Desktop/ticket-bot/server.py", line 93, in respond
    response = self.filter_agent_response(message, sender_id, parse_data, [response_data[0].get('text')])
IndexError: list index out of range
2018-04-23 11:19:31,865:ERROR:Caught an exception during parse: list index out of range
Traceback (most recent call last):
  File "C:/Users/IT/Desktop/ticket-bot/server.py", line 93, in respond
    response = self.filter_agent_response(message, sender_id, parse_data, [response_data[0].get('text')])
IndexError: list index out of range
2018-04-23 11:19:49,978:ERROR:Caught an exception during parse: list index out of range
Traceback (most recent call last):
  File "C:/Users/IT/Desktop/ticket-bot/server.py", line 93, in respond
    response = self.filter_agent_response(message, sender_id, parse_data, [response_data[0].get('text')])
IndexError: list index out of range
